{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "s3www.fullname" . }}
  labels:
    {{- include "s3www.commonLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "s3www.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}
