apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3www.fullname" . }}
  labels:
    {{- include "s3www.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "s3www.selectorLabels" . | nindent 4 }}
