image:
  repository: ${image_repository}
  tag: ${image_tag}

fileToServe:
  sourceUrl: ${file_url}

service:
  type: ClusterIP

metrics:
  enabled: true
  servicemonitor:
    enabled: true

ingress:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

replicaCount: 1
