image:
  repository: ${image_repository}
  tag: ${image_tag}

fileToServe:
  sourceUrl: ${file_url}

service:
  type: ClusterIP

metrics:
  enabled: true
  servicemonitor:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: ${domain_name}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: s3www-tls
      hosts:
        - ${domain_name}

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

replicaCount: 3
